"""Crear tablas base v1.0

Revision ID: 63590237cb51
Revises: 
Create Date: 2025-11-03 17:10:39.418163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63590237cb51'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('registration_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_index(op.f('ix_owners_email'), 'owners', ['email'], unique=True)
    op.create_index(op.f('ix_owners_owner_id'), 'owners', ['owner_id'], unique=False)
    op.create_table('veterinarians',
    sa.Column('veterinarian_id', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('specialization', sa.String(length=200), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('veterinarian_id')
    )
    op.create_index(op.f('ix_veterinarians_email'), 'veterinarians', ['email'], unique=True)
    op.create_index(op.f('ix_veterinarians_license_number'), 'veterinarians', ['license_number'], unique=True)
    op.create_index(op.f('ix_veterinarians_veterinarian_id'), 'veterinarians', ['veterinarian_id'], unique=False)
    op.create_table('pets',
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('species', sa.Enum('dog', 'cat', 'bird', 'rabbit', 'other', name='species_enum'), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], ),
    sa.PrimaryKeyConstraint('pet_id')
    )
    op.create_index(op.f('ix_pets_pet_id'), 'pets', ['pet_id'], unique=False)
    op.create_table('appointments',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('veterinarian_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', 'no_show', name='appointment_status_enum'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.pet_id'], ),
    sa.ForeignKeyConstraint(['veterinarian_id'], ['veterinarians.veterinarian_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_index(op.f('ix_appointments_appointment_id'), 'appointments', ['appointment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_appointment_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_pets_pet_id'), table_name='pets')
    op.drop_table('pets')
    op.drop_index(op.f('ix_veterinarians_veterinarian_id'), table_name='veterinarians')
    op.drop_index(op.f('ix_veterinarians_license_number'), table_name='veterinarians')
    op.drop_index(op.f('ix_veterinarians_email'), table_name='veterinarians')
    op.drop_table('veterinarians')
    op.drop_index(op.f('ix_owners_owner_id'), table_name='owners')
    op.drop_index(op.f('ix_owners_email'), table_name='owners')
    op.drop_table('owners')
    # ### end Alembic commands ###
